### ISSUE TITLE
[BUG] Write Images failed in some devices

### ISSUE THREAD

**Issue by gzsll** [MolotovCherry/kmagick#16]
When I try to convert JPG to PDF, it throws an exception in some devices

E  kmagick::magick_wand: `MagickWand::writeImages()` threw an exception: MagickError("failed to write images")

 D  UnableToCreateTemporaryFile 'magick-_CwoAApjRQXS-O121m7hoaSZ8mdSsJ7y': Read-only file system @ error/blob.c/InjectImageBlob/2772

    val wand = MagickWand()
    wand.readImage(imagePath)
    wand.transformImageColorspace(ColorspaceType.CMYKColorspace)
    wand.writeImage("path/xxx.pdf")

**Comment by MolotovCherry** [comment]
Are you using imagemagick android? If so, have you handled pointing `TMPDIR` to a filesystem which has write privileges on it?

**Comment by gzsll** [comment]
[kmagick](https://github.com/MolotovCherry/kmagick) also need ENV Variable setup?

**Comment by MolotovCherry** [comment]
No, but if you're using Android Imagemagick, it needs setup.

**Comment by gzsll** [comment]
val wand = MagickWand()
wand.readImage(imagePath)
wand.transformImageColorspace(ColorspaceType.CMYKColorspace)
wand.writeImage("path/xxx.pdf")

I use kmagick, some devices can convert succesful, some devices will throw above exception

**Comment by MolotovCherry** [comment]
Have you adjusted the `TMPDIR` env var according to the documentation?

**Comment by MolotovCherry** [comment]
I believe you can also set temporary path in your policy as well
[Android imagemagick policy file](https://github.com/MolotovCherry/Android-ImageMagick7/blob/master/example-app/android/app/src/main/assets/usr/etc/ImageMagick-7/policy.xml)
[imagemagick documentation](https://www.imagemagick.org/script/security-policy.php)

I'm going to make this as solved since these are the two solutions (env var or policy change). But feel free to reply to the issue if you still have questions! 😄
